Numpy Assignment 

Name: Naga Sai Trinaya Chaluvadi

Roll No: 238T1A4282

Batch No: 2


## Section A – Conceptual Understanding



### A1 

**Question:** Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons.


**Answer:**
- **Speed & Efficiency:** NumPy arrays were **107× faster** than Python lists in our performance test.
- **Vectorization:** NumPy allows us to perform operations on the **entire array at once** without explicitly traversing each element.
- **AI/ML Compatibility:** NumPy arrays are widely used across the **Python AI/ML ecosystem**.

In [38]:
import numpy as np
import time 

a=[1,2,3,4,5]
b=np.arange(5)


start = time.time()
result_list = [x * 2 for x in a]
list_time = time.time() - start

# NumPy array operation
start = time.time()
result_array = b * 2
numpy_time = time.time() - start

print("Python List Time :", list_time)
print("NumPy Array Time :", numpy_time)
print("Speedup :", list_time / numpy_time, "x")


Python List Time : 0.0010001659393310547
NumPy Array Time : 0.0


ZeroDivisionError: float division by zero

### A2 

**Question:**
Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets? 

**Answer:**

**Vectorization: Performing an operation on the entire NumPy array at once instead of using a Python loop to process each element.**
 
It makes the code faster and more efficient, especially when working with large datasets.

In [ ]:
import time

start = time.time()
result = a * 2
end = time.time()

print(result)
print("Time:", end - start)

a=[1,2,3,4,5]
start = time.time()
result_list = [x * 2 for x in a]
list_time = time.time() - start
print(result_list)
print("List Time:", list_time)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Time: 0.0010154247283935547
[2, 4, 6, 8, 10]
List Time: 0.0


### A3

**Question**
 For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each

**Answer**

 A * B performs element-wise multiplication and can be used when applying an element-wise mask or scaling values.

A @ B performs matrix multiplication and is commonly used to calculate the output of a neural-network layer.

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([7,8,9,10,11])
print('Element-Wise Multiplication:',a*b)
print('Matrix Multiplication:',a@b)

Element-Wise Multiplication: [ 7 16 27 40 55]
Matrix Multiplication: 145


### A4
**Question**
What is broadcasting in NumPy?

**Answer**

Broadcasting: NumPy allows arrays with different shapes to be used together in element-wise operations by automatically adjusting the smaller array.

General rule: Compare shapes from right to left. The dimensions must be equal or one of them must be 1.

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A.shape)

B = np.array([10, 20, 30])
print(B.shape)
print(A + B)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]


### A5
**Question** 

     flatten() vs ravel()
**Answer**

flatten() → converts an array into 1D and creates a copy of the data.

ravel() → converts an array into 1D and usually returns a view of the original data, so it uses less memory.


In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a.flatten())
print(a.ravel())

[1 2 3 4]
[1 2 3 4]


### A6 

**Question:**

For a 2D array, explain `axis=0` and `axis=1` in an aggregation function such as `np.sum()` or `np.mean()`. Illustrate with a small example.

**Answer:**

axis=0 → gives column-wise result

axis=1 → gives row-wise result

In [ ]:
print(a)
print(a.sum(axis=0))  # Sum along columns
print(a.sum(axis=1)) # Sum along rows

[[1 2]
 [3 4]]
[4 6]
[3 7]


### A7

**Question:** 

Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

**Answer:**

Normalization vs Standardization

Importance: Scaling features puts them on a similar scale, preventing large-valued features from dominating the model.

Normalization: Scales values to a fixed range, usually 0 to 1.

Standardization: Transforms values to have mean 0 and standard deviation 1.



### A8

**Question:** 

Why do functions such as `np.nanmean()` exist? What happens if `np.mean()` is used directly on data containing NaN?

**Answer:**

np.mean() -> includes all values in the calculation. If the data contains NaN, the result will be NaN.

np.nanmean() -> ignores NaN values and calculates the mean using only the available numerical values.


In [ ]:

a = np.array([10, 20, 30, 40, np.nan])

print(np.mean(a))      
print(np.nanmean(a))

nan
25.0


### A9

**Question:** 

In the ML convention `X.shape = (samples, features)`, explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

**Answer:**

An RGB image has 3 dimensions: height, width, and color
 When multiple images are used, we add the number of images as the first dimension.

For 64 RGB images, each of size 128 × 128:

X.shape = (64, 128, 128, 3)
64 → number of images (samples)
128 → height
128 → width
3 → RGB channels

### A10

**Question:** 

Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with `np.random.default_rng(seed)`.

**Answer:**

Reproducibility means getting the same results when an experiment is run again under the same conditions.

Fixing a random seed using np.random.default_rng(seed) makes random values consistent across runs, which helps us debug, compare, and verify our ML experiments.

In [ ]:
rng = np.random.default_rng(42)

## Section B – Predict the Output

### B1

**Predict the output:**

```python
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)
```

**Answer** (3, 3)

### B2 

**Predict the output:**

```python
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])
```

**Answer** [2 5]

### B3

**Predict the output:**

```python
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])
```

**Answer** [10 20]

### B4 

**Predict the output:**

```python
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)
```

**Answer** 

[[10 14]
 [14 20]]

### B5 

**Predict the output:**

```python
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))
```

**Answer** nan 2.3333333333333335

### B6

**Predict the output:**

```python
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)
```

**Answer** [0 1 1]

### B7

**Predict the output:**

```python
a = np.zeros((3, 4))
print(a.ndim, a.size)
```

**Answer** 2 12

### B8

**Predict the output:**

```python
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])
```

**Answer**
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

## Section C – Coding / Implementation

### C1

**Question:** 

Given a 1D NumPy array of exam scores, use `np.where()` to produce labels `'P'` (score >= 40) or `'F'` (score < 40).

In [ ]:
scores = np.array([35, 42, 67, 28, 40, 55])

labels = np.where(scores >= 40, 'P', 'F')

print(labels)

['F' 'P' 'P' 'F' 'P' 'P']


### C2 

**Question:** 

Write a function `standardize(x)` that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

In [ ]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

x = np.array([10, 20, 30, 40, 50])

print(standardize(x))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### C3 

**Question:** 

Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

In [ ]:
batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### C4

**Question:**

 Given X with shape `(100, 5)`, compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

In [ ]:
X = np.random.rand(100, 5)

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print(mean)
print(std)
print(X_standardized)

[0.49713231 0.5114488  0.47292706 0.54873982 0.48530159]
[0.25792242 0.29366084 0.28911196 0.28127013 0.29513782]
[[ 1.25392838 -1.46281429  0.03875048  0.66767402  1.22808455]
 [ 0.38669668  0.90632542  0.86149106  0.12523114  1.58918339]
 [ 1.8806088  -0.23963548 -0.76203333 -0.06901879  1.48700252]
 [ 1.80838771  0.14076057  0.3204534  -1.47087151  0.27453064]
 [-0.15634607  1.36126103  0.93533995  1.38555499  0.75339148]
 [-1.08253005 -1.61273071  0.58390053 -0.67332943 -0.41683102]
 [ 0.32596511 -1.39572377 -1.13613723  0.39517063 -1.01755597]
 [-1.10015565  0.12734008  0.33665657 -1.80357526 -0.55812985]
 [-0.07805702 -0.37764726  1.17870108  0.93910148  0.29978068]
 [-0.26899855  0.77679849  0.71630991  0.71975475  0.63559475]
 [-0.71889547 -0.02179493  0.8685251   0.47017353 -1.59675037]
 [ 0.27619003 -0.10578156  0.77853889  0.16232174  1.3567746 ]
 [ 0.87568703  0.34386728  0.91581041 -0.31250887  1.51994746]
 [-1.2013168  -1.37947162  0.68449937 -0.05593069 -0.79482366]
 [-1

### C5 

**Question:** 

Implement `y_pred = X @ w + b` for a feature matrix X, weight vector w and bias b. Then compute MSE using `y_true`.

In [ ]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_true = np.array([5, 7, 9])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted:", y_pred)
print("MSE:", mse)

Predicted: [4.5 6.  7.5]
MSE: 1.1666666666666667


### C6 

**Question:**
 Using `np.random.default_rng()` with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.


In [ ]:
rng1 = np.random.default_rng(42)
X1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
X2 = rng2.normal(size=(10, 3))

print("Shape:", X1.shape)
print("Identical:", np.array_equal(X1, X2))

Shape: (10, 3)
Identical: True


### C7

**Question:** 

Given a grayscale image as a 2D NumPy array with pixel values in `[0, 255]`, normalize the values to `[0, 1]` using min-max normalization.

In [ ]:
image = np.array([[0, 128, 255],
                  [64, 192, 32]])

normalized = (image - image.min()) / (image.max() - image.min())

print(normalized)

[[0.         0.50196078 1.        ]
 [0.25098039 0.75294118 0.1254902 ]]


### C8 

**Question:**

 Given 4 RGB images of shape `(28, 28, 3)`, stored as shape `(4, 28, 28, 3)`, compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [ ]:
images = np.random.randint(0, 256, size=(4, 28, 28, 3))

average = np.mean(images, axis=(1, 2, 3))

print(average)
print(average.shape)

[127.65433673 127.7329932  127.68112245 127.70280612]
(4,)


## Section D – Applied / Scenario-Based Problems

### D1

**Data Preprocessing Pipeline**

You are given a raw 1D or 2D NumPy array containing NaN values.

Describe, step by step, the NumPy operations you would apply to:
- (a) detect missing values,
- (b) handle them appropriately and justify your strategy, and
- (c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

In [ ]:
data = np.array([10, 20, np.nan, 40, 50], dtype=float)

# Step 1: Detect missing values
print("Missing values:", np.isnan(data).sum())

# Step 2: Handle missing value using mean imputation
data[np.isnan(data)] = np.nanmean(data)

# Step 3: Standardize
standardized = (data - np.mean(data)) / np.std(data)

print("Clean data:", data)
print("Standardized data:", standardized)

Missing values: 1
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


**The code detects missing values, replaces NaN with the mean, and standardizes the cleaned data.**

### D2

**Image Batch Understanding**

Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

Compute the average image of the batch, meaning the element-wise mean across all 16 images.

State the shape of your result and explain why.

In [ ]:
# Create a batch of 16 RGB images
images = np.random.randint(0, 256, size=(16, 64, 64, 3))

# Compute the average image
average_image = np.mean(images, axis=0)

print("Batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


**The code creates 16 RGB images and computes their element-wise average across the batch, producing one RGB image of shape (64, 64, 3).**

### D3

**Debug the Model Code**

The following code contains more than one bug:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)
```

Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.

**Bug 1 — Shape mismatch:

X.shape = (3, 2)
w.shape = (3,)

X has 2 columns, so the weight vector must contain 2 weights. But w contains 3 values. Therefore, X @ w cannot be performed.

Correct:

w = np.array([0.5, 1.0])

Bug 2 — Operator precedence in MSE:

The original code is:

mse = np.mean(y_true - y_pred ** 2)

Because ** has higher precedence than -, Python evaluates it as:

y_true - (y_pred ** 2)

But MSE requires the difference between actual and predicted values to be squared**

In [ ]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


## Section E – Bonus / Challenge


### E1 

**Question:** 

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

In [ ]:

X = np.array([[10, 100],
              [20, 200],
              [30, 300],
              [40, 400]])

min_values = np.min(X, axis=0)
max_values = np.max(X, axis=0)

X_normalized = (X - min_values) / (max_values - min_values)

print(X_normalized)

[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


### E2 

**Question:**

 Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as: Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).

In [ ]:
scores = np.array([35, 40, 55, 70, 75, 90])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print(result)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']
